// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9ZRnUfrNCXBS2f-ECGv3c_og8P3g5mI',
    appId: '1:303208096330:web:f99b4c3fe44067e457fcb3',
    messagingSenderId: '303208096330',
    projectId: 'mednext-1c699',
    authDomain: 'mednext-1c699.firebaseapp.com',
    storageBucket: 'mednext-1c699.appspot.com',
    measurementId: 'G-MGW757VKYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSEW8EWCbYothWpgebMmnXYEAdv0StHE',
    appId: '1:303208096330:android:b8547de5655c528257fcb3',
    messagingSenderId: '303208096330',
    projectId: 'mednext-1c699',
    storageBucket: 'mednext-1c699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCH9BH2HBuUeLTLM89b_lWwWigwGM0-A',
    appId: '1:303208096330:ios:0c486775d0f807b757fcb3',
    messagingSenderId: '303208096330',
    projectId: 'mednext-1c699',
    storageBucket: 'mednext-1c699.appspot.com',
    iosBundleId: 'com.mednext.mednextnew',
  );
}
